from pyquery import PyQuery
x=input("q1 ")
html=PyQuery(x)
t = html('div.title').text()
art = html('p.article').text()
print('\n',t,"1")
print(art,'\n')

if input("y/n") == str('y') or input("y/n") ==  str ("y"):
    x2=input("q2 ")
    html=PyQuery(x2)
    t2 = html('div.title').text()
    art2 = html('p.article').text()
    print('\n',t2,"2")
    print(art2,'\n')

if input("y/n") == str('y') or input("y/n") == str ("y"):
    x3=input("q3 ")
    html=PyQuery(x3)
    t3 = html('div.title').text()
    title3 = html("span.article_tit").text()
    article3 = html("div.article").text()
    q3 = html("p.article.ques").text()
    script3 =html('div.audio_topic').text()
    print('\n',t3,"3")
    print(title3)
    print(article3,'\n')
    print(q3,'\n')
    print("Task 3 Script\n",script3,'\n')
if input("y/n") == str('y') or input("y/n") == str ("y"):
    x4=input("q4 ")
    html=PyQuery(x4)
    t4 = html('div.title').text()
    title4 = html("span.article_tit").text()
    article4 = html("div.article").text()
    q4 = html("p.article.ques").text()
    script4 =html('div.audio_topic').text()
    print('\n',t4,"4")
    print(title4,)
    print(article4,'\n')
    print(q4)
    print("\nTask 4 Script\n",script4,'\n')

if input("y/n") == str('y') or input("y/n") == str ("y"):
    x5=input("q5 ")
    html=PyQuery(x5)
    title5 = html("div.title").text()
    q5= html("p.article.ques").text()
    script5 =html('div.audio_topic').text()
    print('\n')
    print(title5,'5')
    print(q5)
    print("\nTask 5 Script")
    print(script5,'\n')
    
if input("y/n") == str('y') or input("y/n") == str ("y"):
    x6=input("q6 ")
    html=PyQuery(x6)
    title6 = html("div.title").text()
    q6= html("p.article.ques").text()
    script6 =html('div.audio_topic').text()
    print('\n')
    print(title6,'6')
    print(q6)
    print("\nTask 6 Script\n")
    print(script6,'\n')